docs/create/index-create.mdx
docs/explore/index-explore.mdx
docs/guides/indexing/indexing-querying.mdx
docusaurus.config.js
package.json
sidebars.js
src/css/_article.scss
src/css/components/_hero.scss
src/theme/Hero/index.js
src/theme/Languages/index.js
yarn.lock

We tried to be more descriptive with our commit titles - this is all the bugs that we could do as of tonight without addl' design or questions answered - more tomorrow!

Bugherd progress

---

docs/howtos/frauddetection/index-frauddetection.mdx

Fixed Indentation in code

---

docs/develop/dotnet/index-dotnet.mdx

Spotted an incorrectly placed semi-colon (meant to be a colon)

minor grammatical fix

---

docs/develop/java/index-java.mdx

Fixed a wrong link for the Redis Streams in action.

Fixed a wrong link

---

docs/develop/python/fastapi/index-fastapi.mdx
docs/develop/python/index-python.mdx
sidebars.js
src/theme/LayoutHead/index.js

Adds a tutorial about using Redis with FastAPI.

Using Redis with FastAPI

---

docs/develop/node/node-crash-course/advancedstreams/index-advancedstreams.mdx
docs/develop/node/node-crash-course/checkinswithstreams/index-checkinswithstreams.mdx
docs/develop/node/node-crash-course/coursewrapup/index-coursewrapup.mdx
docs/develop/node/node-crash-course/introducingredisinsight/index-introducingredisinsight.mdx
docs/develop/node/node-crash-course/introductiontomodules/index-introductiontomodules.mdx
docs/develop/node/node-crash-course/redisandnodejs/index-redisandnodejs.mdx
docs/develop/node/node-crash-course/redisbloom/index-redisbloom.mdx
docs/develop/node/node-crash-course/redisearch/index-redisearch.mdx
docs/develop/node/node-crash-course/redisjson/index-redisjson.mdx
docs/develop/node/node-crash-course/sessionstorage/index-sessionstorage.mdx
docs/develop/node/node-crash-course/welcome/index-welcome.mdx
docs/develop/node/node-crash-course/whatisredis/index-whatisredis.mdx

Updates the Node Redis Crash Course to use redis.com URLs and Simon's updated job title.

Updated content for new company name and Simon's job title.

---

README.md

Added a note about this in case it trips anyone else up.

Adds note about Node 16 / yarn install issues

---

docs/develop/dotnet/aspnetcore/rate-limiting/fixed-window/index-rate-limiting.mdx
docs/develop/dotnet/aspnetcore/rate-limiting/index-rate-limiting.mdx
docs/develop/dotnet/aspnetcore/rate-limiting/index-sliding-rate-limiter.md
docs/develop/dotnet/aspnetcore/rate-limiting/sliding-window/index-sliding-rate-limiter.md
sidebars.js

Adding fixed and sliding window rate limiter tutorial for ASP.NET Core

Adding fixed & sliding window rate limiter tutorial for ASP.NET Core

---

docs/develop/node/node-crash-course/advancedstreams/index-advancedstreams.mdx
docs/develop/node/node-crash-course/caching/index-caching.mdx
docs/develop/node/node-crash-course/checkinswithstreams/index-checkinswithstreams.mdx
docs/develop/node/node-crash-course/coursewrapup/index-coursewrapup.mdx
docs/develop/node/node-crash-course/domainobjectswithhashes/index-domainobjectswithhashes.mdx
docs/develop/node/node-crash-course/index-node-crash-course.mdx
docs/develop/node/node-crash-course/introducingredisinsight/index-introducingredisinsight.mdx
docs/develop/node/node-crash-course/introductiontomodules/index-introductiontomodules.mdx
docs/develop/node/node-crash-course/managingsuccess/index-managingsuccess.mdx
docs/develop/node/node-crash-course/redisandnodejs/index-redisandnodejs.mdx
docs/develop/node/node-crash-course/redisbloom/index-redisbloom.mdx
docs/develop/node/node-crash-course/redisearch/index-redisearch.mdx
docs/develop/node/node-crash-course/redisjson/index-redisjson.mdx
docs/develop/node/node-crash-course/runningtheapplication/index-runningtheapplication.mdx
docs/develop/node/node-crash-course/sampleapplicationoverview/index-sampleapplicationoverview.mdx
docs/develop/node/node-crash-course/sessionstorage/index-sessionstorage.mdx
docs/develop/node/node-crash-course/welcome/index-welcome.mdx
docs/develop/node/node-crash-course/whatisredis/index-whatisredis.mdx

Using the new author system to add myself as the author of the Node crash course pages.

Adds author to crash course.

---

docusaurus.config.js

A Minor correction in the twitter URL.

Fixed the twitter link

---

.gitignore

Now ignores swp, bak, tmp, log etc files.

Added some extra things to gitignore.

---

docs/create/heroku/herokujava/index-herokujava.mdx
docs/create/heroku/herokunodejs/index-herokunodejs.mdx
docs/create/heroku/herokupython/index-herokupython.mdx
docs/create/heroku/index-heroku.mdx
docs/create/heroku/portal/index-heroku.mdx
docs/create/heroku/ratelimiting-go/index-ratelimitinggo.mdx

Added couple of Heroku tutorials and structured it under one bucket.

Added Heroku Tutorial Series

---

docs/howtos/redisjson/redisjson-cheatsheet/index-redisjson-cheatsheet.mdx

Fix typo on index-redisjson-cheatsheet.mdx

---

docs/develop/node/gettingstarted/index-gettingstarted.mdx

This updates node-redis examples for v 4 and also changes the ioredis example to be the same as the node-redis one... using scan behavior on a sorted set in both clients.
Closes #183

Updated Node intro for node-redis 4 and to make node-redis the primary choice.

---

docs/get-involved/devcember/index-devcember.mdx

Adds first weekend call to action and stream times for Dec 6/7.

Adds first weekend and 6/7 times.

---

docs/get-involved/devcember/index-devcember.mdx

Adds Day 7 topic/embed.

---

docs/get-involved/devcember/index-devcember.mdx

Sets up Day 8 DEVcember Hyperloglog.

---

docs/get-involved/devcember/index-devcember.mdx

Adds pub sub day.

---

docs/develop/dotnet/aspnetcore/caching/basic/index-basic-api-caching.md
sidebars.js

Basic ASP.NET Core Caching tutorial using NWS Weather API.

Basic ASP.NET Core caching tutorial.

---

docs/explore/what-is-redis/index-what-is-redis.mdx

Fixed the title & optimised the link @wjohnsto

Fixed the title of this tutorial

---

docs/create/netlify/getting-started-with-netlify/index-getting-started-with-netlify.mdx

Just a single Netlify logo fixed.

Fixed the Netlify Featured Image

---

docs/develop/deno/index.deno.mdx

This PR fixes the sequence of numbering for Deno & Redis blog.

Minor numbering fix for Deno blog

---

docs/create/aws/bidding-on-aws/index-bidding-on-aws.mdx
docs/create/heroku/herokunodejs/index-herokunodejs.mdx
docs/create/heroku/portal/index-heroku.mdx
docs/howtos/analytics/index-analytics.mdx
docs/howtos/hackernews/index-hackernews.mdx
docs/howtos/herokujava/index-herokujava.mdx
docs/howtos/herokunodejs/index-herokunodejs.mdx
docs/howtos/herokupython/index-herokupython.mdx
docs/howtos/ratelimiting/index-ratelimiting.mdx
docs/howtos/redisgraph/redisgraphmovies/index-redisgraphmovies.mdx
docs/howtos/redisgraphmovies/index-redisgraphmovies.mdx
docs/howtos/redisjson/shoppingcart/index-shoppingcart.mdx
docs/howtos/shoppingcart/index-shoppingcart.mdx

Updated text across a few articles and picked up a couple of other small formatting updates.

Changed environmental variables to environment variables.

---

docusaurus.config.js
src/theme/DocItem/index.tsx
src/theme/DocItem/styles.module.css

This pull request reinstates the authors block at the top of each article.  For some reason files related to the `DocItem` component were missing so I re-added them.  Please give this a thorough check over before merging!
Closes #265

Reinstated authors.

---

docs/create/docker/nodejs-nginx-redis/index-nodejs-nginx-redis.mdx
docs/create/windows/index-windows.mdx

This PR:
- Fixes https://github.com/redis-developer/redis-developer.github.io/issues/288
- Changes the title from "How to install Redis on Windows 10" to a generic "How to install Redis on Windows"

Fixed the nginx.conf

---

docs/create/windows/index-windows.mdx
docs/operate/index-operate.mdx

The devops branch didn't get merge, hence triggering it again.

Add Operate section

---

docs/create/aws/index-aws.mdx

Fix typo on AWS page

---

docs/get-involved/redis-live/index-redis-live.mdx

I was gonna stream one thing but a Discord user gave me a better idea!

changed todays streaming plan

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds entries on the live page for a couple of 102 course setup streams.

Added RU102 course setup Twitch shows.

---

docs/create/aws/redis-on-aws/index-redis-on-aws.mdx
docs/create/azure/portal/index-azure-portal.mdx
docs/create/cloud/aws/index-aws.mdx
docs/create/cloud/azure/index-azure.mdx
docs/create/cloud/gcp/index-gcp.mdx
docs/create/cloud/index-cloud.mdx.orig
docs/create/cloud/rediscloud/index-recloud.mdx
docs/create/docker/redis-on-docker/index-redis-on-docker.mdx
docs/create/gcp/index-gcp.mdx
docs/create/heroku/herokujava/index-herokujava.mdx
docs/create/heroku/herokunodejs/index-herokunodejs.mdx
docs/create/heroku/herokupython/index-herokupython.mdx
docs/create/heroku/portal/index-heroku.mdx.python
docs/howtos/herokujava/index-herokujava.mdx
docs/howtos/herokunodejs/index-herokunodejs.mdx
docs/howtos/herokupython/index-herokupython.mdx
docs/howtos/redisbloom/index-redisbloom.mdx
docs/howtos/redisearch/index-redisearch.mdx
docs/howtos/redisgraph/getting-started/index-gettingstarted.mdx
docs/howtos/redistimeseries/getting-started/index-redistimeseries.mdx
docs/modules/redisbloom/index-redisbloom.mdx
docs/modules/redisearch/index-redisearch.mdx
docs/modules/redisgraph/index-redisgraph.mdx
docs/modules/redisjson/index-redisjson.mdx
docs/modules/redistimeseries/index-redistimeseries.mdx

Found a load of cases where we had a "Next Step" sub-heading and fixed them all to say "Next Steps".

Changed Next Step -> Next Steps.

---

docs/get-involved/redis-live/index-redis-live.mdx

Added a stream Simon will do on June 28th 2022 at 3pm UTC.

Adds Simon RU102J stream June 28 2022.

---

docs/get-involved/hacktoberfest/index-hacktoberfest.mdx

Puts some things in the past tense and makes sure all the videos are there and that there are no upcoming events shown.

Amends the Hacktoberfest page

---

docs/explore/redisinsightv2/getting-started/index-gettingstarted.mdx

Copy change for marketing... @RedisTMill @wjohnsto please resolve any similar issues in future with your own PRs.

Removed Elastic UI closes #362

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved your stream to the past tab, and linked to the YouTube of it (I also added the YouTube video to your playlist on the channel: https://www.youtube.com/playlist?list=PL83Wfqi-zYZHSnOXH3kCkgyfk3Rqo_wzH)

Moved 26 July stream to past, added video link.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved Savannah and Simon's stream to the past tab, added YT video link.  Removed Guy's stream from the schedule for 29th.

Moved 29 july to past deleted guy 29 july

---

docs/get-involved/redis-live/index-redis-live.mdx

I realize mine is in UTC on the recurring tab.  This is what makes sense to me.

Added my recurring stream and first instance of it.

---

docs/get-involved/redis-live/index-redis-live.mdx
docusaurus.config.js

Updated Simon's link.

---

docs/get-involved/redis-insiders/michael-owolabi/index-michael-owolabi.mdx

Update my Redis insider profile with my social links

Add redis insider Michael social link to profile

---

docusaurus.config.js

* Add link to redis insider Michael author name

Add link to redis insider Michael author name

---

docs/create/windows/index-windows.mdx

add steps after open windows store

---

docs/get-involved/redis-live/index-redis-live.mdx

Move Guy's stream from Friday and linked to the YouTube video.

Moved Aug 12 to past, added video link.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved Savannah's August 16th stream to the past tab, added link to it on YouTube, also added it to Savannah's YouTube playlist.

Moved Savannah's Aug 16 stream to past, added yt link.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved the Aug 26 stream to Past and linked its video.

Moved Aug 26 stream and linked video.

---

docs/get-involved/redis-live/index-redis-live.mdx

Add recurring discord office hours

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved both the Friday streams and added their videos.

Moved Sept 2 streams adds videos.

---

docs/develop/php/index-php.mdx

Fix extra "r" in PHP develop page

---

docs/create/homebrew/index-homebrew.mdx
docs/develop/golang/index-golang.mdx
docs/develop/php/index-php.mdx
docs/develop/python/index-python.mdx

SEO meta tag changes like title & description

title/ description modified as per SEO recommendations by chris

---

docs/develop/php/index-php.mdx

* Properly capitalize PHP and PhpRedis
* Fix typo in "PONG"

Update the PHP Redis documentation page

---

docs/get-involved/redis-live/index-redis-live.mdx

Also moved past events to past, added their video links and added a missing event that happened this week.

Moved This Week on Discord Oct 14 to top

---

docs/get-involved/redis-live/index-redis-live.mdx

Updated the schedule to move Oct 14th stream to the past and add the link to it on YouTube.

Moved Oct 14 This Week on Discord to past.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved Simon and Savannah's streams to past tab, adds video link.  Adds Steve's latest stream in past tab.

Updates schedule for Oct 27.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved office hours Oct 27 to past.

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds the stream 'Do birds dream in JSON?' to upcoming events and recurring events.

adds justin stream

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds Things on Thursdays for Nov 3 2022.

Adds Simon's stream for Nov 3.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved various past events to past, added YouTube links and updated descriptions, added Simon's Dec 15th IoT event.

Moved old events, adds Simon Dec 15 event.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moves streams that are now in the pasts, adds their links to YouTube.

Moved Dec 9 week on Discord & Dec 8 204.

---

docs/get-involved/redis-live/index-redis-live.mdx

Loads up some upcoming events for early January.

Moved past shows, adds some Jan ones.

---

docs/get-involved/redis-live/index-redis-live.mdx

Now I know what I'm doing on Jan 5th I've updated the title for the stream to be more appropriate.

Updated title for Jan 5 livestream, adds Jan 12 stream.

---

docusaurus.config.js

Some people got promoted and/or moved to other jobs - updating their bios accordingly.

Updated some job titles.

---

docs/get-involved/redis-live/index-redis-live.mdx

Removed Jan 5 events.

---

docs/get-involved/redis-live/index-redis-live.mdx

* Updated staff for week on Discord
* Removed University office hours
* Removed Jan 19th IoT stream
* Added Savannah's Jan 17th stream video link
* Moved other past events to past tab

Reflect changes in staff for upcoming streams.

---

docs/get-involved/redis-live/index-redis-live.mdx

Added Simon's stream, moved previous week's streams to past tab, added youtube links.

Updated schedule for week of Jan 23.

---

docs/get-involved/redis-live/index-redis-live.mdx

Moved my Feb 16th livestream to the past tab, added YouTube link.

Moved Feb 16 livestream to past.

---

docs/get-involved/redis-live/index-redis-live.mdx

Updated the schedule after Simon's live stream on Feb 20th 2023.  Also added my Feb 24th stream and various other schedule updates that needed doing.

Moved Feb 17, 20, 21 streams to past adds links.

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds Simon's show for March 2nd, moved his 24th Feb to past and added YouTube link.

Added March 2 stream moved Feb 24 adds link.

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds my next stream at 1pm UTC March 14th.

Added March 14 Simon stream.

---

docs/get-involved/redis-live/index-redis-live.mdx

Added march 10th stream into the past tab (it wasn't in the upcoming).  also moved my March 14th stream and added link.

Updated for March 10 stream.

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds Savannah's stream from March 24 2023.

Adds March 24 Savannah stream.

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds Savannah's March 31 livestream.

Added March 31 livestream.

---

docs/get-involved/redis-live/index-redis-live.mdx

Simplified this page to reflect how we use it at the moment.

Rework live stream page to remove tabs and scheduled section

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds Simon's June 1st livestream.

Added June 1 livestream.

---

docs/get-involved/redis-live/index-redis-live.mdx

Adds Simon's next live stream.

Added June 9th stream.

---

docs/howtos/solutions/real-time-inventory/common-rti/customer-proofs.mdx

We are no longer using this customer proof

removed Dick's customer proof link
