- docs/develop/golang/index-golang.mdx
The showcased links point to wrong website locations. This PR addresses that issue
> Fix Golang Technical Articles & Whitepapers links

- docusaurus.config.js
Partially addresses #152 - removes the blue Hacktoberfest banner from the top of the site.
> Removed announcement bar now Hacktoberfest is over.

- src/theme/DocItem/index.tsx
Removes a `console.log` that I accidentally left in place while developing the show authors feature.  Sorry about that!
> Removed console log I left in by accident.

- docs/get-involved/hacktoberfest/index-hacktoberfest.mdx
- src/theme/DocItem/index.tsx
Makes the next/previous cards configurable... By default they are on, and you can turn them off by adding this to your document's front matter:
```yaml
useNextPrev: false
```
This preserves the current behaviour of all pages having these links, but allows us to override this for some where we don't want this (see the Hacktoberfest page for an example here).
> Makes the next/prev links configurable, defaults to on.

- docs/explore/datadog/index-datadog.mdx
In the new blog post - https://developer.redis.com/explore/datadog/ - in the title, DataDog should be Datadog
> updating DataDog to Datadog

- docs/get-involved/devcember/index-devcember.mdx
- sidebars.js
> Adds Devcember project page.

- docusaurus.config.js
This is a PR to add $200 coupon code for Redis Enterprise Cloud.
> Announcing $200 Off Coupon code for Redis Enterprise Cloud

- docs/get-involved/devcember/index-devcember.mdx
Adds the YouTube embed for day 6's livestream.  This can be merged immediately.
> Adds video embed for day 6.

- docs/create/kubernetes/index-kubernetes.mdx
- docs/create/kubernetes/kubernetes-operator/index-kubernetes-operator.mdx
Hi @simonprickett Content team suggested to change the title of this blog post and hence pushed the changes.
> Fixed the title

- docs/create/aws/terraform/index-terraform.mdx
Modified the "Further References" links and kept it simple text with links rather than just links.
> Add AWS and Terraform Tutorial

- docusaurus.config.js
Prior this PR, there was no way to tell if we were reading a new version of the page besides reading it entirely.
Now we'll get something like this:
> Add Docusaurus flag to show the last update time

- docs/develop/dotnet/streams/blocking-reads/blocking-reads.md
- docs/develop/dotnet/streams/blocking-reads/cs-redis/cs-redis.md
- docs/develop/dotnet/streams/blocking-reads/service-stack/service-stack.md
- docs/develop/dotnet/streams/streams-basics.md
- sidebars.js
Adding a tutorial for handling Redis Streams with .NET, because of the unique nature of the .NET ecosystem the main library does not support blocking reads with Redis Streams, consequentially I added tutorials for two alternative libraries that developers can use if they really need blocking stream reads.
> Redis Streams with .NET tutorials

- docs/explore/redisinsightv2/index-redisinsightv2.mdx
- docs/explore/redisinsightv2/redisearch/index-redisearch.mdx
RediSearch under RedisInsight is rightly called as "Plugin" rather than tool. Hence, this PR fixes it.
> Fixed the title for RediSearch Plugin

- docs/develop/java/spring/getting-started.mdx
- docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive-lua.mdx
- docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window-reactive.mdx
- docs/develop/java/spring/rate-limiting/fixed-window/index-fixed-window.mdx
- docs/develop/java/spring/rate-limiting/getting-started/getting-started.mdx
- docs/develop/java/spring/redis-and-spring-course/index-redis-and-spring-course.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_1/index-lesson_1.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_2/index-lesson_2.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_3/index-lesson_3.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_4/index-lesson_4.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_5/index-lesson_5.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_6/index-lesson_6.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_7/index-lesson_7.mdx
- docs/develop/java/spring/redis-and-spring-course/lesson_9/index-lesson_9.mdx
- docs/explore/redisinsight/redisearch/index-redisearch.mdx
- docs/howtos/shoppingcart/index-shoppingcart.mdx
Updates pages to use the new author system, where we have that author set up in the config file.
> Updated many pages to use the newer author system.

- docs/howtos/redisjson/using-python/index-usingpython.mdx
In python, the docs tutorial(https://developer.redis.com/howtos/redisjson/using-python/) does not work for the hello world for rejson.
It appears to want `root_path()` instead of `rootPath()`
```python
python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> from redis.commands.json.path import Path
>>> client = redis.Redis(host='localhost', port=6379, db=0)
>>> jane = {
...      'name': "Jane", 
...      'Age': 33, 
...      'Location': "Chawton"
...    }
>>> 
>>> client.json().set('person:1', Path.rootPath(), jane)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: type object 'Path' has no attribute 'rootPath'
>>> dir(Path)
['__class__', …
```
> docs(rejson): python rootPath() -> root_path()

- docs/develop/python/redis-om/index-redis-om.mdx
Encourages use of Redis Stack, updates a couple of URLs to their new redis.io homes, avoiding redirects.
> Updated for new Search and JSON doc URLs and to use redis-stack not redismod

- docs/howtos/redisgraph/using-dotnet/index-usingdotnet.md
- docs/howtos/redistimeseries/using-dotnet/index.md
The redis-stack-server docker is now the prefered way for trying out the latest version. This PR attempts to address the locations accordingly, and point to this docker.
> Updating docker to point to redis-stack-server

- docs/get-involved/redis-live/index-redis-live.mdx
Move Steve's stream to the past tab, add the youtube link for it.
> Moved 27 July stream to past, added video link.

- docs/create/cloud/rediscloud/index-recloud.mdx
- docs/create/rediscloud/index-recloud.mdx
This was rendering as markdown not an image... See #383 for a previous attempt to fix this that didn't work for me.  I'll raise a separate issue to fix numerous other instance of this.
Test locally:
```
yarn start
```
Then visit `http://localhost:3000/create/cloud/rediscloud` and ensure that the launchpad image at the end renders and is a link to the launchpad.
> Fixes launchpad image static path.

- docs/get-involved/redis-live/index-redis-live.mdx
Moves Steve's Aug 3 stream to the past tab and adds a YouTube link for it.
> Moved Aug 3 stream to past, adds link.

- docs/get-involved/redis-live/index-redis-live.mdx
Move Steve's event to the past, add video link for it.  Delete Simon's failed Aug 11 livestream.
> Cleaned up live events page.

- docs/get-involved/redis-live/index-redis-live.mdx
Adds video for 23 Aug live stream, moved it to past tab.  I also added it to the relevant playlists on YouTube and deleted a couple of spam comments there.
> Moved Aug 23 stream to past, added video.

- docs/get-involved/redis-live/index-redis-live.mdx
Moved Simon's 8th Sept stream to past, added video link.  Added Steve's 7th Sept stream to past (it wasn't in upcoming so didn't remove it from there).  Also adds Simon's Sept 22 stream.
> Updated for Steve 7 Sept and Simon 8 Sept streams adds Simon Sept 22 stream.

- docs/create/docker/redis-on-docker/index-redis-on-docker.mdx
Fixing the image markup for at the bottom of https://developer.redis.com/create/docker/redis-on-docker/
| Before | After |
| :--: | :--: |
| ![image](https://user-images.githubusercontent.com/45119518/191476100-03c3676a-ed84-45e9-8f26-995a13c73b2b.png)| ![image](https://user-images.githubusercontent.com/45119518/191476131-1e08d42e-98f6-47a3-9c15-f657fb233aaa.png) |
> fix: corrected launchpad image in redis-on-docker index

- docs/howtos/redisjson/using-java/index-usingjava.mdx
Simple adjust to fix maven's version on example:
```diff
<dependency>
<groupId>redis.clients</groupId>
<artifactId>jedis</artifactId>
-<version>4.0.0<version>
+<version>4.0.0</version>
</dependency>
```
> Hotfix: end maven's version tag on Java RedisJSON documentation example

- docs/develop/python/fastapi/index-fastapi.mdx
- `aioredis-py` 2.0.0 is not a beta version anymore (https://github.com/aio-libs/aioredis-py/releases)
- update `poetry add aioredis-py` to `poetry add aioredis` (https://aioredis.readthedocs.io/en/latest/getting-started/#installation)
> Update FastAPI tutorial doc

- docs/get-involved/redis-live/index-redis-live.mdx
I noticed office hours and my IoT streams had the wrong times on the recurring tab.
> Fixed recurring stream times.

- docs/guides/security/how-to-use-tls-with-redis-enterprise/how-to-use-ssl-tls-with-redis-enterprise.mdx
- docs/howtos/security/tls.mdx
`readFileSync` accepts an object or a string as the second parameter. The examples use `(encoding = 'ascii')` which assigns `ascii` as a string to `encoding` variable and then returns its value. Therefore, it is semantically correct but I think the intent here was to pass an object instead of assigning the string to a variable.
> Fix readFileSync options parameter

- docs/get-involved/redis-live/index-redis-live.mdx
Updates the schedule with:
* Added Simon's February 2nd livestream
* Added Justin's Jan 23 livestream to Past tad, abbs YT link
* Added Savannah's Jan 24 livestream to Past tad, abbs YT link
* Moved Simon's Jan 26th livestream to Past tab, adds YT link
> Jan 26 schedule update.

- docs/howtos/redisjson/using-python/index-usingpython.mdx
While redis-py supports rejson v1 and v2 APIs, the default root_path is '.' and not '$'. This specifically exists so as to not break our existing customers, and is in the process of changing (though it is a breaking change). As a result, I'm updating the public example, so that at least our users are using the multi-select v2 API from the onset.
> Updating json example to use the json v2 root path

- docs/get-involved/redis-live/index-redis-live.mdx
Updated the schedule after Simon's March 2nd livestream.  @justincastilla @savynorem  note the upcoming schedule is now empty, please add anything you have coming up in subsequent PRs.
> Schedule update March 2.  Moved Plane Spotting Episode 4 adds link.

- docs/get-involved/redis-live/index-redis-live.mdx
Adds Simon's next IoT stream on April 27th.  Pointing people to the YouTube link this time for a change rather than the Twitch channel.
> Added April 27th IoT stream.
